apiVersion: v1
kind: Service
metadata:
  name: instagram-copy-frontend-service
spec:
  selector:
    app: instagram-copy-frontend
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  type: LoadBalancer